name: 'Analyze data'

on: workflow_dispatch

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        working-directory: ./scraper
      - name: Generate analyzer output
        run: python analyzer.py
        working-directory: ./scraper
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: analyzer-output
          path: ./scraper/analyzer-output/*