name: 'Collect Data'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python collector.py
      - name: Set current date as env variable
        run: echo "now=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - uses: EndBug/add-and-commit@v5
        with:
          add: 'data.json data.csv'
          message: ${{ env.now }}
          branch: data
