name: 'Collect Data'

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # - name: Cache pip
      #   uses: actions/cache@v2
      #   with:
      #     # This path is specific to Ubuntu
      #     path: ~/.cache/pip
      #     # Look to see if there is a cache hit for the corresponding requirements file
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        working-directory: ./scraper
      - name: Scrape!
        env:
          FB_EMAIL: ${{ secrets.fb_email }}
          FB_PASS: ${{ secrets.fb_pass }}
        run: python converter.py
        working-directory: ./scraper
      - name: Set current date as env variable
        id: date
        run: echo ::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%SZ')
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.date.outputs.today }}
          tag_name: ${{ github.run_number }}
      - name: Upload Release Asset - data.csv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scraper/data-converted.csv
          asset_name: data-converted.csv
          asset_content_type: text/csv
      - name: Upload Release Asset - logs.txt
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scraper/logs2.txt
          asset_name: logs2.txt
          asset_content_type: text/plain
