name: 'Collect Data'

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Scrape!
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          python main.py
        working-directory: ./scraper
      - name: Set current date as env variable
        id: date
        run: echo ::set-output name=today::$(date +'%Y-%m-%dT%H:%M:%SZ')
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.date.outputs.today }}
          tag_name: ${{ github.run_number }}
      - name: Upload Release Asset - data.csv
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scraper/data.csv
          asset_name: data.csv
          asset_content_type: text/csv
