name: 'Scrape NUSWhispers API'

on:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Scrape!
        run: python collector.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-data
          path: |
            data.csv
            data.json
            error.txt
